=== STLAB-DINFO/Empedocle/stlab-modules/stlab-reflection-lite/src/main/resources/facts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.stlab.dsi.unifi.it/reflection/facts"
	xmlns:tns="http://www.stlab.dsi.unifi.it/reflection/facts"
	elementFormDefault="qualified">

	<element name="textual">
		<complexType>
			<simpleContent>
				<extension base="string">
					<attribute name="type" type="string" use="required"/>
				</extension>
			</simpleContent>
		</complexType>
	</element>

	<element name="temporal">
		<complexType>
			<simpleContent>
				<extension base="dateTime">
					<attribute name="type" type="string" use="required"/>
				</extension>
			</simpleContent>
		</complexType>
	</element>

	<element name="qualitative">
		<complexType>
			<simpleContent>
				<extension base="string">
					<attribute name="type" type="string" use="required"/>
				</extension>
			</simpleContent>
		</complexType>
	</element>

	<element name="quantitative">
		<complexType>
			<simpleContent>
				<extension base="float">
					<attribute name="type" type="string" use="required"/>
					<attribute name="um" type="string" use="required"/>
				</extension>
			</simpleContent>
		</complexType>
	</element>

	<element name="composite">
		<complexType>
			<choice maxOccurs="unbounded">
				<element ref="tns:textual"/>
				<element ref="tns:temporal"/>
				<element ref="tns:qualitative"/>
				<element ref="tns:quantitative"/>
				<element ref="tns:composite"/>
			</choice>
			<attribute name="type" type="string" use="required"/>
		</complexType>	
	</element>
	

</schema>

=== STLAB-DINFO/Empedocle/stlab-modules/stlab-reflection-lite/target/test-classes/samples.xml
<?xml version="1.0" encoding="UTF-8"?>
<composite xmlns="http://www.stlab.dsi.unifi.it/reflection/facts"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.stlab.dsi.unifi.it/reflection/facts ../../main/resources/facts.xsd "
	type="">

	<textual type="textualTypeUuid">
		Some Text
	</textual>
	<temporal type="temporalTypeUuid">2002-05-30T09:00:00</temporal>
	<quantitative type="quantitativeTypeUuid" um="umUuid">123.5</quantitative>
	<qualitative type="qualitativeTypeUuid">uuid</qualitative>

	<composite type="compositeTypeUuid">
		<textual type="textualTypeUuid">
			Some Text
		</textual>
		<temporal type="temporalTypeUuid">2002-05-30T09:00:00</temporal>
		<quantitative type="quantitativeTypeUuid" um="umUuid">123.5</quantitative>
		<qualitative type="qualitativeTypeUuid">uuid</qualitative>
		<composite type="compositeTypeUuid">
			<textual type="textualTypeUuid">
				Some Text
			</textual>
		</composite>
	</composite>

</composite>
